### PR TITLE
Doc: Fix typo

### PR DESCRIPTION
**Pull request by shlyakpavel**

### CODE REVIEW

**Comment by jameshilliard** [comment]
Please send this as a patch to the mailing list, this project does not accept contributions via github, see:
https://sbabic.github.io/swupdate/contributing.html

**Comment by shlyakpavel** [comment]
I'm not interested in swupdate at the moment, but I'd appreciate if someone else reported that to the maling list.

**Comment by MarkJonas** [comment]
I created a matching patch on the mailing list. See https://groups.google.com/g/swupdate/c/gtgoBRHkEmA

**Comment by MarkJonas** [comment]
> I created a matching patch on the mailing list. See https://groups.google.com/g/swupdate/c/gtgoBRHkEmA

Merged to master, see 00cf7347ce84bacd40bae2ef1dba54a3a6b65168

@sbabic @shlyakpavel   I propose to close this PR.

**Comment by shlyakpavel** [comment]
Thank you!

**Pull request closed without merging**
