### PR TITLE
Update control

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by alexmyczko** [comment]
Yes debian maintainer, i can download your mentor dsc package and try to build it, it won't. debuild bails out. That is what the changes are for.

I don't know how i can fix my Signed-off-by thing...

**Comment by sbabic** [comment]
On 24/10/18 17:09, Alex Myczko wrote:
> Yes debian maintainer, i can download your mentor dsc package and try to
> build it, it won't. debuild bails out. That is what the changes are for.
> 
> I don't know how i can fix my Signed-off-by thing...
> 

Ok, good. I can do myself, I will add this line to the git commit:

Signed-off-by: Alex Myczko <alex@aiei.ch>

After that, I will push into -master.

Regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Comment by alexmyczko** [comment]
ok I managed to build a package, almost. However debian/control needs also these be added:
mtd-dev, liblua5.2-dev, libzmq3-dev
and the mtd-utils package needs to build a mtd-dev (or libmtd-dev):
https://salsa.debian.org/debian/mtd-utils

fails at linking ubi and mtd:
/usr/bin/ld: cannot find -lubi
/usr/bin/ld: cannot find -lmtd

http://phd-sid.ethz.ch/debian/swupdate/

**Comment by sbabic** [comment]
Hi Alex,

On 25/10/18 00:35, Alex Myczko wrote:
> ok I managed to build a package, almost. However debian/control needs
> also these be added:
> mtd-dev, liblua5.2-dev, libzmq3-dev

Ok - I fix this, thanks.

> and the mtd-utils package needs to build a mtd-dev (or libmtd-dev):
> https://salsa.debian.org/debian/mtd-utils
> 

This is correct, but there is no mtd-utils-dev (just mtd-utils). We
could drop MTD feature (at least for now) from the debian configuration,
and then the library is not required. Dropping MTD, also UBI will be
dropped.

However, SWUpdate is thought for embedded systems, and on most of them
we need MTD to write into the flash. That's the reason I built with mtd
the package and makes sense to build with it. The library is linked
statically and it is not needed on system after build.

Anyway, it could be done in two steps: first a package without MTD, then
with it when mtd-utils-dev is available.

I have also thought to build libmtd into rules, but it is a big hack and
I have not found any example in debian that let me think that such as
behavior can be accepted...

> fails at linking ubi and mtd:
> /usr/bin/ld: cannot find -lubi
> /usr/bin/ld: cannot find -lmtd
> 
> http://phd-sid.ethz.ch/debian/swupdate/

ok - I will take your changes and post as patches, and then merge them
into -master.

Best regards,
Stefano

-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: sbabic@denx.de
=====================================================================

**Pull request closed without merging**
