### PR TITLE
Update sw-description.rst

### PR DESCRIPTION
**Pull request by nike-17**
grammar fixes

### CODE REVIEW

**Comment by nike-17** [comment]
Some minor grammar issues

**Comment by jameshilliard** [comment]
Please send this as a patch to the mailing list, this project does not accept contributions via github, see:
https://sbabic.github.io/swupdate/contributing.html

**Comment by MarkJonas** [comment]
I sent a mostly equivalent patch to the mailing list. See https://groups.google.com/g/swupdate/c/FOIg0PUEMYY

**Comment by MarkJonas** [comment]
> I sent a mostly equivalent patch to the mailing list. See https://groups.google.com/g/swupdate/c/FOIg0PUEMYY

Merged to master, see f84a54ab4d453ba4a6e676570b80dbddb58ded07

@sbabic @nike-17 I propose to close this PR.

**Pull request closed without merging**
